### ISSUE TITLE
CLI: Command to show/save/delete/load configuration

### ISSUE THREAD

**Issue by zimventures** [zimventures/cpdk#10]
Built-in commands are needed to provide the ability to show, save, delete, and load the entire configuration. 

A global command "config" will be available with the following sub-commands:
- save
- delete
- load
- list
- show

The show command will also be aliased to "show config" which better matches other show commands.

```
Global> config save backup.cfg
Writing backup.cfg to disk
Global> config list
backup.cfg
Global> config delete
Are you sure you want to delete the entire configuration? [yes/no]  yes
Global> config load backup.cfg
Loading backup.cfg
Global> 
```

**Comment by xujianin1988** [comment]
I can take care of this one if you want.

**Comment by zimventures** [comment]
Absolutely! Let's talk today if you need any clarifications.

**Comment by xujianin1988** [comment]
A couple questions about this issue:

1. When we create a many-to-many relationship. Should this relationship show up on both end (model object) ? Also, when we load the configuration, we could just add_ref on either object and the result will be the same, is this correct ? Is the following behavior a bug ?

Global>show server
test2-relation - None
	None:None
	Enabled: None

Global>show virtual
Virtual Server: Vippy
	Port: None
	Enabled: None
	Virtual IPs:
		vip_test

	Servers:
		test2-relation

Virtual Server: test2
	Port: None
	Enabled: None
	Servers:
		test2-relation

Global>

2. Do we need to put the config file path into setting.py as an user configurable parameter ?

**Comment by zimventures** [comment]
There's an outstanding issue to limit how many-to-many relationships are displayed. In the example above, you don't want to allow the user to configure virtual servers FOR servers, but you do need a many-to-many relationship. 

I guess we'll have to address that issue as part of this issue, otherwise, we're going to allow double-relationships to occur. 

2) Yes, let's add a field in settings.py for the config file name.

**Comment by xujianin1988** [comment]
Okay, so basically the above behavior is correct since we don't want to create and display virtual servers for servers, but what confused me a little bit is where you add the constraints for only displaying servers for virtual servers ? The show_xxx method looks exactly the same:

        elif arg_list[0] == "server":
            zmq_cmd = None
            if len(arg_list) == 1:
                zmq_cmd = {"t": "list", "o": "Server"}
            elif len(arg_list) == 2:
                zmq_cmd = {"t": "list", "o": "Server", "on": arg_list[1]}
            Global.zmq_socket.send_json(zmq_cmd)
            reply = Global.zmq_socket.recv_json()
            if reply["status"] != "ok":
                print reply["message"]
                return
            for r in reply["result"]:
                m = getattr(Global.models["Server"], "show", None)
                print m(r) if m else default_show(r)

        elif arg_list[0] == "virtual":
            zmq_cmd = None
            if len(arg_list) == 1:
                zmq_cmd = {"t": "list", "o": "VirtualServer"}
            elif len(arg_list) == 2:
                zmq_cmd = {"t": "list", "o": "VirtualServer", "on": arg_list[1]}
            Global.zmq_socket.send_json(zmq_cmd)
            reply = Global.zmq_socket.recv_json()
            if reply["status"] != "ok":
                print reply["message"]
                return
            for r in reply["result"]:
                m = getattr(Global.models["VirtualServer"], "show", None)
                print m(r) if m else default_show(r)


If we want to constraint the user to create virtual servers FOR servers, should we add an info dict (info is a parameter in super class constructor) when we create the relationship in model.py ? like

virtual_servers = relationship('VirtualServer',
                                               secondary=Server_VS_Map,
                                               info={"add": "restrict"})

When we create the server CLI,  we could read the info dict and skip the "do_add" and "do_remove".

If the scenario is like this, this should be a separate issue because we only need to restrict the user to create and display virtual servers FOR servers on CLI level, but not the database level, that being said, when we load the configuration, we could create this relationship from either place (server or virtual). Is my understanding correct ?

**Comment by zimventures** [comment]
Let's chat about this on Wednesday. Going to be way easier than trying to
explain via email :)
